// VIDEOGAMES
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
export const DELETE_DETAIL_VIDEOGAME = "DELETE_DETAIL_VIDEOGAME";
export const RESET_DETAIL_TO_HOME = "RESET_DETAIL_TO_HOME";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
// GENRES
export const GET_ALL_GENRES = "GET_ALL_GENRES";

//FILTERS
export const GENRE_FILTER = "GENRE_FILTER";
export const ORIGIN_FILTER = "ORIGIN_FILTER";
export const FILTER_BY_ORDER = "FILTER_BY_ORDER";
export const FILTER_BY_RATING = "FILTER_BY_RATING ";
export const RESET_FILTERS = "RESET_FILTERS";
